- name: check updates
  hosts: all
  become: yes
  tasks:
  - name: check updates
    pacman:
      update_cache: yes

- name: Setup Arch Linux desktop with dwm
  hosts: all
  become: yes
  vars_files:
    - group_vars/all.yml
  roles:
    - user
    - pacman
    - core-apps
    - dotfiles
    - role: zsh
      when: setup_zsh | default(false) | bool
    - role: dwm
      when: install_dwm | default(false) | bool
    - "{{ browser }}"
    - role: terminal_browsers
      when: install_terminal_browsers | default(false) | bool
    - role: aur
      when: use_aur | default(false) | bool
    - group
    - authorized_keys
    - role: power-management
      when: configure_tlp | default(false) | bool
    - sshd
    #- role: reboot
    #  when: reboot_after_setup | default(false) | bool
